# Generated by Django 5.2.6 on 2025-09-23 04:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('publish_datetime', models.DateTimeField(blank=True, null=True)),
                ('publish_time_text', models.CharField(blank=True, max_length=64)),
                ('image_url', models.URLField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('content_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-publish_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('business_date', models.DateField()),
                ('match_datetime', models.DateTimeField()),
                ('league', models.CharField(max_length=128)),
                ('league_id', models.CharField(blank=True, max_length=64)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('round_name', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed')], default='scheduled', max_length=16)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('odds_home', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('odds_draw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('odds_away', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('latest_article_synced_at', models.DateTimeField(blank=True, null=True)),
                ('latest_ai_summary_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['match_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('ai_base_url', models.URLField(default='https://api.openai.com/v1/chat/completions')),
                ('ai_api_key', models.CharField(blank=True, max_length=255)),
                ('ai_model', models.CharField(default='gpt-4o-mini', max_length=128)),
                ('article_prompt', models.TextField(blank=True)),
                ('match_prompt', models.TextField(blank=True)),
                ('consensus_prompt', models.TextField(blank=True)),
                ('update_interval_minutes', models.PositiveIntegerField(default=180)),
                ('last_update_at', models.DateTimeField(blank=True, null=True)),
                ('last_article_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sogou_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=64, unique=True)),
                ('league', models.CharField(blank=True, max_length=128)),
                ('league_id', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('logo_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, max_length=512)),
                ('key_points', models.TextField(blank=True)),
                ('verdict', models.CharField(choices=[('home_win', 'Home Win'), ('away_win', 'Away Win'), ('draw', 'Draw'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('predicted_score', models.CharField(blank=True, max_length=32)),
                ('total_goals', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('confidence', models.PositiveIntegerField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='matches.article')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='matches.match'),
        ),
        migrations.CreateModel(
            name='AiInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, max_length=512)),
                ('key_points', models.TextField(blank=True)),
                ('verdict', models.CharField(choices=[('home_win', 'Home Win'), ('away_win', 'Away Win'), ('draw', 'Draw'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('predicted_score', models.CharField(blank=True, max_length=32)),
                ('total_goals', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('confidence', models.PositiveIntegerField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('provider', models.CharField(blank=True, max_length=128)),
                ('risk_factors', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='matches.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statistics', models.JSONField(blank=True, default=dict)),
                ('injuries', models.JSONField(blank=True, default=dict)),
                ('shooters', models.JSONField(blank=True, default=dict)),
                ('future_matches', models.JSONField(blank=True, default=dict)),
                ('history', models.JSONField(blank=True, default=dict)),
                ('odds_info', models.JSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='matches.match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('recommendation_points', models.JSONField(blank=True, default=list)),
                ('confidence_level', models.CharField(blank=True, max_length=64)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='matches.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('article_summary', 'Article Summary'), ('match_summary', 'Match Summary'), ('alert', 'Alert')], max_length=32)),
                ('headline', models.CharField(blank=True, max_length=512)),
                ('details', models.TextField(blank=True)),
                ('verdict', models.CharField(choices=[('home_win', 'Home Win'), ('away_win', 'Away Win'), ('draw', 'Draw'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('predicted_score', models.CharField(blank=True, max_length=32)),
                ('total_goals', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('confidence', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='matches.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.team'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['business_date'], name='matches_mat_busines_2bc133_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_datetime'], name='matches_mat_match_d_52ef6e_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['league'], name='matches_mat_league_f6ac15_idx'),
        ),
    ]
