# Generated by Django 4.2.7 on 2025-09-22 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('league', models.CharField(max_length=128)),
                ('round_name', models.CharField(blank=True, max_length=64)),
                ('venue', models.CharField(blank=True, max_length=128)),
                ('match_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed')], default='scheduled', max_length=16)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('odds_home', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('odds_draw', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('odds_away', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('last_checked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['match_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=32)),
                ('league', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('coach', models.CharField(blank=True, max_length=128)),
                ('stadium', models.CharField(blank=True, max_length=128)),
                ('crest_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('summary', models.TextField(blank=True)),
                ('recommendation_points', models.JSONField(blank=True, default=list)),
                ('confidence_level', models.CharField(blank=True, max_length=32)),
                ('risk_notes', models.TextField(blank=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='matches.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='matches.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='matches.team'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('summary', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=128)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='matches.match')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='internal', max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('verdict', models.CharField(blank=True, help_text='home/draw/away', max_length=32)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('predicted_score', models.CharField(blank=True, max_length=32)),
                ('total_goals', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('headline', models.CharField(blank=True, max_length=256)),
                ('key_points', models.TextField(blank=True)),
                ('risk_factors', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='matches.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(max_length=32)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('possession_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shots_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passing_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('form', models.CharField(blank=True, help_text='Recent form string such as W-W-D-L-W', max_length=128)),
                ('form_description', models.TextField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='matches.team')),
            ],
            options={
                'ordering': ['-season'],
                'unique_together': {('team', 'season')},
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_datetime'], name='matches_mat_match_d_52ef6e_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['league'], name='matches_mat_league_f6ac15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('match_datetime', 'home_team', 'away_team')},
        ),
    ]
